import { MigrationInterface, QueryRunner } from "typeorm";

export class AddBlogPublicityFields1756639837664 implements MigrationInterface {
    name = 'AddBlogPublicityFields1756639837664'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "follows_following_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "follows_follower_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_blogId_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_commentId_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_postId_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_actor_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_recipient_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_files_user"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_FILES_CONTEXT"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_c4f9a7bd77b489e711277ee5986"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_55d9c167993fed3f375391c8e31"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_posts_blogId"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_6c2e267ae764a9413b863a29342"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_ea832c070ef3f903d1db1ce7b9d"`);
        await queryRunner.query(`ALTER TABLE "analytics_events" DROP CONSTRAINT "FK_12f66e6068f7e89865310f68838"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "FK_6199f13e2ff401739b476841eae"`);
        await queryRunner.query(`ALTER TABLE "post_files" DROP CONSTRAINT "FK_2c299cc914a0501e319e3c00262"`);
        await queryRunner.query(`ALTER TABLE "post_files" DROP CONSTRAINT "FK_a1c97d2fe5db827c1906c3bef65"`);
        await queryRunner.query(`DROP INDEX "public"."idx_follows_follower"`);
        await queryRunner.query(`DROP INDEX "public"."idx_follows_following"`);
        await queryRunner.query(`DROP INDEX "public"."idx_follows_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_recipient_read"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_recipient_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_actor"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FILES_CONTEXT_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EMAIL_CODE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EXPIRES_AT"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_type_check"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "follows_follower_id_following_id_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "displayName"`);
        await queryRunner.query(`ALTER TABLE "files" DROP COLUMN "is_optimized"`);
        await queryRunner.query(`ALTER TABLE "files" DROP COLUMN "expires_at"`);
        await queryRunner.query(`ALTER TABLE "files" DROP COLUMN "file_status"`);
        await queryRunner.query(`ALTER TABLE "files" DROP COLUMN "optimized_url"`);
        await queryRunner.query(`ALTER TABLE "blogs" ADD "isPublic" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "blogs" ADD "allowComments" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('FOLLOW', 'POST_LIKE', 'COMMENT', 'COMMENT_REPLY', 'BLOG_POST', 'MENTION')`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "type" "public"."notifications_type_enum"`);
        await queryRunner.query(`UPDATE "notifications" SET "type" = 'FOLLOW' WHERE "type" IS NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "type" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "read" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "content_type"`);
        await queryRunner.query(`DROP TYPE "public"."posts_content_type_enum"`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "content_type" character varying DEFAULT 'html'`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "UQ_e42cf55faeafdcce01a82d24849"`);
        await queryRunner.query(`ALTER TABLE "api_keys" ALTER COLUMN "keyId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "api_keys" ALTER COLUMN "keySecret" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."audit_logs_action_enum" RENAME TO "audit_logs_action_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('user_created', 'user_updated', 'user_deleted', 'user_suspended', 'user_banned', 'user_activated', 'user_role_changed', 'post_updated', 'post_deleted', 'post_published', 'post_unpublished', 'comment_updated', 'comment_deleted', 'report_reviewed', 'report_resolved', 'report_dismissed', 'report_escalated', 'admin_logout', 'admin_access_denied', 'settings_updated', 'bulk_action_performed')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "action" TYPE "public"."audit_logs_action_enum" USING "action"::"text"::"public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum_old"`);
        await queryRunner.query(`CREATE INDEX "IDX_c518e3988b9c057920afaf2d8c" ON "follows" ("following_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_54b5dc2739f2dea57900933db6" ON "follows" ("follower_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ffcc26e0e374c307f94ee989d2" ON "notifications" ("recipient_id", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_df95345b0832f6a18cb4794056" ON "notifications" ("recipient_id", "read") `);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "UQ_8109e59f691f0444b43420f6987" UNIQUE ("follower_id", "following_id")`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_54b5dc2739f2dea57900933db66" FOREIGN KEY ("follower_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_c518e3988b9c057920afaf2d8c0" FOREIGN KEY ("following_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_5332a4daa46fd3f4e6625dd275d" FOREIGN KEY ("recipient_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_20f8b51fd9655c0b69feed5efc6" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_93c464aaf70fb0720dc500e93c8" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9faba56a12931cf4e38f9dddb49" FOREIGN KEY ("commentId") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_55d9c167993fed3f375391c8e31" FOREIGN KEY ("blogId") REFERENCES "blogs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_6c2e267ae764a9413b863a29342" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_ea832c070ef3f903d1db1ce7b9d" FOREIGN KEY ("blogId") REFERENCES "blogs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_ea832c070ef3f903d1db1ce7b9d"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_6c2e267ae764a9413b863a29342"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_55d9c167993fed3f375391c8e31"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9faba56a12931cf4e38f9dddb49"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_93c464aaf70fb0720dc500e93c8"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_20f8b51fd9655c0b69feed5efc6"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_5332a4daa46fd3f4e6625dd275d"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_c518e3988b9c057920afaf2d8c0"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_54b5dc2739f2dea57900933db66"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "UQ_8109e59f691f0444b43420f6987"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df95345b0832f6a18cb4794056"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ffcc26e0e374c307f94ee989d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54b5dc2739f2dea57900933db6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c518e3988b9c057920afaf2d8c"`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum_old" AS ENUM('user_created', 'user_updated', 'user_deleted', 'user_suspended', 'user_banned', 'user_activated', 'user_role_changed', 'post_created', 'post_updated', 'post_deleted', 'post_published', 'post_unpublished', 'comment_created', 'comment_updated', 'comment_deleted', 'report_created', 'report_reviewed', 'report_resolved', 'report_dismissed', 'report_escalated', 'admin_login', 'admin_logout', 'admin_access_denied', 'settings_updated', 'bulk_action_performed')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "action" TYPE "public"."audit_logs_action_enum_old" USING "action"::"text"::"public"."audit_logs_action_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."audit_logs_action_enum_old" RENAME TO "audit_logs_action_enum"`);
        await queryRunner.query(`ALTER TABLE "api_keys" ALTER COLUMN "keySecret" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "api_keys" ALTER COLUMN "keyId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "UQ_e42cf55faeafdcce01a82d24849" UNIQUE ("key")`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "content_type"`);
        await queryRunner.query(`CREATE TYPE "public"."posts_content_type_enum" AS ENUM('markdown', 'html')`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "content_type" "public"."posts_content_type_enum" NOT NULL DEFAULT 'html'`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "read" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "blogs" DROP COLUMN "allowComments"`);
        await queryRunner.query(`ALTER TABLE "blogs" DROP COLUMN "isPublic"`);
        await queryRunner.query(`ALTER TABLE "files" ADD "optimized_url" character varying`);
        await queryRunner.query(`ALTER TABLE "files" ADD "file_status" character varying NOT NULL DEFAULT 'temp'`);
        await queryRunner.query(`ALTER TABLE "files" ADD "expires_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "files" ADD "is_optimized" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "displayName" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "follows_follower_id_following_id_key" UNIQUE ("follower_id", "following_id")`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_type_check" CHECK (((type)::text = ANY ((ARRAY['FOLLOW'::character varying, 'POST_LIKE'::character varying, 'COMMENT'::character varying, 'COMMENT_REPLY'::character varying, 'BLOG_POST'::character varying, 'MENTION'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "IDX_EXPIRES_AT" ON "email_verifications" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_EMAIL_CODE" ON "email_verifications" ("code", "email") `);
        await queryRunner.query(`CREATE INDEX "IDX_FILES_CONTEXT_ID" ON "files" ("context_id") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_actor" ON "notifications" ("actor_id") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_recipient_created" ON "notifications" ("createdAt", "recipient_id") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_recipient_read" ON "notifications" ("read", "recipient_id") `);
        await queryRunner.query(`CREATE INDEX "idx_follows_created" ON "follows" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_follows_following" ON "follows" ("following_id") `);
        await queryRunner.query(`CREATE INDEX "idx_follows_follower" ON "follows" ("follower_id") `);
        await queryRunner.query(`ALTER TABLE "post_files" ADD CONSTRAINT "FK_a1c97d2fe5db827c1906c3bef65" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_files" ADD CONSTRAINT "FK_2c299cc914a0501e319e3c00262" FOREIGN KEY ("fileId") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "FK_6199f13e2ff401739b476841eae" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "analytics_events" ADD CONSTRAINT "FK_12f66e6068f7e89865310f68838" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_ea832c070ef3f903d1db1ce7b9d" FOREIGN KEY ("blogId") REFERENCES "blogs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_6c2e267ae764a9413b863a29342" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_posts_blogId" FOREIGN KEY ("blogId") REFERENCES "blogs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_55d9c167993fed3f375391c8e31" FOREIGN KEY ("blogId") REFERENCES "blogs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_c4f9a7bd77b489e711277ee5986" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_FILES_CONTEXT" FOREIGN KEY ("context_id") REFERENCES "file_contexts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_files_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_recipient_id_fkey" FOREIGN KEY ("recipient_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_postId_fkey" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_commentId_fkey" FOREIGN KEY ("commentId") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_blogId_fkey" FOREIGN KEY ("blogId") REFERENCES "blogs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "follows_follower_id_fkey" FOREIGN KEY ("follower_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "follows_following_id_fkey" FOREIGN KEY ("following_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
