import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1757158710842 implements MigrationInterface {
    name = 'InitialSchema1757158710842'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."comment_likes_type_enum" AS ENUM('like', 'dislike')`);
        await queryRunner.query(`CREATE TABLE "comment_likes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "commentId" uuid NOT NULL, "type" "public"."comment_likes_type_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ec6698ead14ad945033ebb2f1b9" UNIQUE ("userId", "commentId"), CONSTRAINT "PK_2c299aaf1f903c45ee7e6c7b419" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text NOT NULL, "isDeleted" boolean NOT NULL DEFAULT false, "likesCount" integer NOT NULL DEFAULT '0', "dislikesCount" integer NOT NULL DEFAULT '0', "authorId" uuid NOT NULL, "postId" uuid NOT NULL, "parentCommentId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."file_contexts_contexttype_enum" AS ENUM('profile', 'post', 'blog', 'system')`);
        await queryRunner.query(`CREATE TYPE "public"."file_contexts_purpose_enum" AS ENUM('avatar', 'cover', 'thumbnail', 'content', 'attachment', 'logo', 'banner', 'favicon', 'general')`);
        await queryRunner.query(`CREATE TABLE "file_contexts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "contextType" "public"."file_contexts_contexttype_enum" NOT NULL, "contextId" uuid, "ownerId" uuid NOT NULL, "purpose" "public"."file_contexts_purpose_enum" NOT NULL, "version" integer NOT NULL DEFAULT '1', "isActive" boolean NOT NULL DEFAULT true, "fileCount" integer NOT NULL DEFAULT '0', "totalSize" bigint NOT NULL DEFAULT '0', "maxFiles" integer, "maxFileSize" bigint, "allowedTypes" text, "metadata" jsonb, "general" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7a3d2ec3e1ac72d1bdc78eb1328" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_69f54b3906f28ad3e0f20e684d" ON "file_contexts" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_36ba37bc75cb1ec04d6d4033e0" ON "file_contexts" ("contextType", "contextId") `);
        await queryRunner.query(`CREATE TABLE "files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "original_name" character varying NOT NULL, "file_name" character varying NOT NULL, "file_key" character varying NOT NULL, "file_url" character varying NOT NULL, "file_size" integer NOT NULL, "mime_type" character varying NOT NULL, "file_type" character varying NOT NULL DEFAULT 'general', "user_id" uuid NOT NULL, "context_id" uuid, "s3_bucket" character varying, "s3_region" character varying, "checksum" character varying, "isOptimized" boolean NOT NULL DEFAULT false, "metadata" jsonb, "expiresAt" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6c16b9093a142e0e7613b04a3d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f7eec60ca11e796ab5b713516d" ON "files" ("context_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7435dbb7583938d5e7d137604" ON "files" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a02ba48ab7537f785bdc47b7b" ON "files" ("file_key") `);
        await queryRunner.query(`CREATE TABLE "blogs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying, "name" character varying, "description" character varying, "thumbnailUrl" character varying, "isPublic" boolean NOT NULL DEFAULT true, "allowComments" boolean NOT NULL DEFAULT true, "userId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7b18faaddd461656ff66f32e2d7" UNIQUE ("slug"), CONSTRAINT "UQ_50205032574e0b039d655f6cfd3" UNIQUE ("userId"), CONSTRAINT "PK_e113335f11c926da929a625f118" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "slug" character varying, "content" text NOT NULL, "content_markdown" text, "content_type" character varying DEFAULT 'html', "content_rendered_at" TIMESTAMP, "thumbnail" character varying, "thumbnail_image_id" uuid, "isPublished" boolean NOT NULL DEFAULT false, "viewCount" integer NOT NULL DEFAULT '0', "likeCount" integer NOT NULL DEFAULT '0', "commentCount" integer NOT NULL DEFAULT '0', "tags" text, "category" character varying, "authorId" uuid NOT NULL, "blogId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "publishedAt" TIMESTAMP, "version" integer NOT NULL, CONSTRAINT "UQ_54ddf9075260407dcfdd7248577" UNIQUE ("slug"), CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c81be77ac4b528ea4f2c94fcfb" ON "posts" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_c5a322ad12a7bf95460c958e80" ON "posts" ("authorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_33d16435acab5d7cb1970157de" ON "posts" ("isPublished") `);
        await queryRunner.query(`CREATE TABLE "follows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "follower_id" uuid NOT NULL, "following_id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8109e59f691f0444b43420f6987" UNIQUE ("follower_id", "following_id"), CONSTRAINT "PK_8988f607744e16ff79da3b8a627" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c518e3988b9c057920afaf2d8c" ON "follows" ("following_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_54b5dc2739f2dea57900933db6" ON "follows" ("follower_id") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('FOLLOW', 'POST_LIKE', 'COMMENT', 'COMMENT_REPLY', 'BLOG_POST', 'MENTION')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recipient_id" uuid NOT NULL, "actor_id" uuid NOT NULL, "postId" uuid, "commentId" uuid, "blogId" uuid, "type" "public"."notifications_type_enum" NOT NULL, "read" boolean NOT NULL DEFAULT false, "message" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ffcc26e0e374c307f94ee989d2" ON "notifications" ("recipient_id", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_df95345b0832f6a18cb4794056" ON "notifications" ("recipient_id", "read") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'admin', 'moderator')`);
        await queryRunner.query(`CREATE TYPE "public"."users_authprovider_enum" AS ENUM('local', 'google', 'kakao', 'github')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "password" character varying(255), "username" character varying(100), "profileImage" character varying(500), "bio" character varying(1000), "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "authProvider" "public"."users_authprovider_enum" NOT NULL DEFAULT 'local', "providerId" character varying(255), "isEmailVerified" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "lastLoginAt" TIMESTAMP, "refreshToken" character varying(500), "refreshTokenExpiresAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "primaryIdentityId" character varying, "lastLoginProvider" character varying(50), "accountVerifiedAt" TIMESTAMP, "accountSecurityLevel" character varying(20) DEFAULT 'basic', CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ace513fa30d485cfd25c11a9e4" ON "users" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."user_identities_provider_enum" AS ENUM('local', 'google', 'kakao', 'github', 'naver')`);
        await queryRunner.query(`CREATE TABLE "user_identities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "provider" "public"."user_identities_provider_enum" NOT NULL, "providerId" character varying NOT NULL, "providerEmail" character varying, "providerData" jsonb, "linkedAt" TIMESTAMP NOT NULL DEFAULT now(), "lastUsedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_a810154198446b51fdf3f227c5f" UNIQUE ("provider", "providerId"), CONSTRAINT "PK_e23bff04e9c3e7b785e442b262c" PRIMARY KEY ("id")); COMMENT ON COLUMN "user_identities"."providerData" IS 'Additional provider-specific data (profile picture, name, etc.)'`);
        await queryRunner.query(`CREATE INDEX "IDX_26d8925842789f2d3b8c093ab3" ON "user_identities" ("provider") `);
        await queryRunner.query(`CREATE INDEX "IDX_084cef3785217102f222e90ea7" ON "user_identities" ("userId") `);
        await queryRunner.query(`CREATE TABLE "email_verifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "code" character varying(6) NOT NULL, "isVerified" boolean NOT NULL DEFAULT false, "attemptCount" integer NOT NULL DEFAULT '0', "expiresAt" TIMESTAMP NOT NULL, "verifiedAt" TIMESTAMP, "sessionToken" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1ea2921e767f83cd44c0af203f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_442ebfa56e39cc1a9bd8467742" ON "email_verifications" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_58575e75914e0b6832685808b1" ON "email_verifications" ("email", "code") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('user_created', 'user_updated', 'user_deleted', 'user_suspended', 'user_banned', 'user_activated', 'user_role_changed', 'post_updated', 'post_deleted', 'post_published', 'post_unpublished', 'comment_updated', 'comment_deleted', 'report_reviewed', 'report_resolved', 'report_dismissed', 'report_escalated', 'admin_logout', 'admin_access_denied', 'settings_updated', 'bulk_action_performed')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" "public"."audit_logs_action_enum" NOT NULL, "entityType" character varying(50) NOT NULL, "entityId" uuid, "previousData" jsonb, "newData" jsonb, "metadata" jsonb, "performedById" uuid NOT NULL, "ipAddress" character varying, "userAgent" character varying, "sessionId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_371007aca0b12c07d6d2dbdb83" ON "audit_logs" ("performedById") `);
        await queryRunner.query(`CREATE INDEX "IDX_13c69424c440a0e765053feb4b" ON "audit_logs" ("entityType", "entityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE TYPE "public"."reports_type_enum" AS ENUM('post', 'comment', 'user')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_reason_enum" AS ENUM('spam', 'hate_speech', 'inappropriate_content', 'harassment', 'copyright_violation', 'misinformation', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_status_enum" AS ENUM('pending', 'under_review', 'resolved', 'dismissed', 'escalated')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_actiontaken_enum" AS ENUM('no_action', 'warning_issued', 'content_removed', 'user_suspended', 'user_banned')`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."reports_type_enum" NOT NULL, "reason" "public"."reports_reason_enum" NOT NULL, "description" text, "targetId" uuid NOT NULL, "reportedById" uuid NOT NULL, "status" "public"."reports_status_enum" NOT NULL DEFAULT 'pending', "actionTaken" "public"."reports_actiontaken_enum", "moderatorNotes" text, "reviewedById" uuid, "reviewedAt" TIMESTAMP, "priority" integer NOT NULL DEFAULT '1', "metadata" jsonb, "ipAddress" character varying, "userAgent" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_546a6297a776c8413251354225" ON "reports" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_047d4304f5141509edcd89820f" ON "reports" ("reportedById") `);
        await queryRunner.query(`CREATE INDEX "IDX_dab4d78b3be05c1ca4a626f57f" ON "reports" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_67286c99c7756fb0961b60c58f" ON "reports" ("type", "targetId") `);
        await queryRunner.query(`CREATE TABLE "api_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying, "keyId" character varying, "keySecret" character varying, "signingSecret" character varying, "name" character varying NOT NULL, "description" character varying, "userId" uuid NOT NULL, "blogId" uuid NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "lastUsedAt" TIMESTAMP, "expiresAt" TIMESTAMP, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_8c29253f53d643ca3ca4d7eb020" UNIQUE ("keyId"), CONSTRAINT "PK_5c8a79801b44bd27b79228e1dad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "analytics_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "anonymousId" character varying(255), "eventType" character varying(100) NOT NULL, "eventData" jsonb, "sessionId" character varying(255), "userAgent" text, "ipAddress" character varying(45), "referrer" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5d643d67a09b55653e98616f421" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a880d68cf02094abb4d55eed54" ON "analytics_events" ("anonymousId") `);
        await queryRunner.query(`CREATE INDEX "IDX_42589da045825b9fba75e0c51c" ON "analytics_events" ("sessionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_38c954e266791189dfd7b6ffc4" ON "analytics_events" ("eventType", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_89639a7cf8b3cd156a5d3b9a30" ON "analytics_events" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" SERIAL NOT NULL, "token" character varying NOT NULL, "userId" uuid NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "used" boolean NOT NULL DEFAULT false, "usedAt" TIMESTAMP, "ipAddress" character varying, "userAgent" character varying, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_ab673f0e63eac966762155508ee" UNIQUE ("token"), CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f75f11ca4ed69b941336c5d0e3" ON "password_reset_tokens" ("expiresAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ab673f0e63eac966762155508e" ON "password_reset_tokens" ("token") `);
        await queryRunner.query(`CREATE TABLE "post_likes" ("postId" uuid NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "PK_30ee85070afe5b92b5920957b1c" PRIMARY KEY ("postId", "userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6999d13aca25e33515210abaf1" ON "post_likes" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_37d337ad54b1aa6b9a44415a49" ON "post_likes" ("userId") `);
        await queryRunner.query(`CREATE TABLE "post_files" ("postId" uuid NOT NULL, "fileId" uuid NOT NULL, CONSTRAINT "PK_211edbcd05443e46105ae36e84d" PRIMARY KEY ("postId", "fileId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a12706e0fd90132ab2ffa9b0b1" ON "post_files" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1755b7f4061d5ece60967f00e4" ON "post_files" ("fileId") `);
        await queryRunner.query(`ALTER TABLE "comment_likes" ADD CONSTRAINT "FK_34d1f902a8a527dbc2502f87c88" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_likes" ADD CONSTRAINT "FK_abbd506a94a424dd6a3a68d26f4" FOREIGN KEY ("commentId") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_4548cc4a409b8651ec75f70e280" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_e44ddaaa6d058cb4092f83ad61f" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_4875672591221a61ace66f2d4f9" FOREIGN KEY ("parentCommentId") REFERENCES "comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_a7435dbb7583938d5e7d1376041" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_f7eec60ca11e796ab5b713516d4" FOREIGN KEY ("context_id") REFERENCES "file_contexts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blogs" ADD CONSTRAINT "FK_50205032574e0b039d655f6cfd3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_152b0f8575bdeb47131d9318a66" FOREIGN KEY ("thumbnail_image_id") REFERENCES "files"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_c5a322ad12a7bf95460c958e80e" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_55d9c167993fed3f375391c8e31" FOREIGN KEY ("blogId") REFERENCES "blogs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_54b5dc2739f2dea57900933db66" FOREIGN KEY ("follower_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_c518e3988b9c057920afaf2d8c0" FOREIGN KEY ("following_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_5332a4daa46fd3f4e6625dd275d" FOREIGN KEY ("recipient_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_20f8b51fd9655c0b69feed5efc6" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_93c464aaf70fb0720dc500e93c8" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9faba56a12931cf4e38f9dddb49" FOREIGN KEY ("commentId") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_identities" ADD CONSTRAINT "FK_084cef3785217102f222e90ea7c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_371007aca0b12c07d6d2dbdb83a" FOREIGN KEY ("performedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_047d4304f5141509edcd89820fc" FOREIGN KEY ("reportedById") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_26b00552a46acf717aa502b1596" FOREIGN KEY ("reviewedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_6c2e267ae764a9413b863a29342" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_ea832c070ef3f903d1db1ce7b9d" FOREIGN KEY ("blogId") REFERENCES "blogs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "analytics_events" ADD CONSTRAINT "FK_5a6943770a0e7335b8c9b401aa6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_d6a19d4b4f6c62dcd29daa497e2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "FK_6999d13aca25e33515210abaf16" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "post_files" ADD CONSTRAINT "FK_a12706e0fd90132ab2ffa9b0b1e" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "post_files" ADD CONSTRAINT "FK_1755b7f4061d5ece60967f00e4b" FOREIGN KEY ("fileId") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "post_files" DROP CONSTRAINT "FK_1755b7f4061d5ece60967f00e4b"`);
        await queryRunner.query(`ALTER TABLE "post_files" DROP CONSTRAINT "FK_a12706e0fd90132ab2ffa9b0b1e"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "FK_6999d13aca25e33515210abaf16"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_d6a19d4b4f6c62dcd29daa497e2"`);
        await queryRunner.query(`ALTER TABLE "analytics_events" DROP CONSTRAINT "FK_5a6943770a0e7335b8c9b401aa6"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_ea832c070ef3f903d1db1ce7b9d"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_6c2e267ae764a9413b863a29342"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_26b00552a46acf717aa502b1596"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_047d4304f5141509edcd89820fc"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_371007aca0b12c07d6d2dbdb83a"`);
        await queryRunner.query(`ALTER TABLE "user_identities" DROP CONSTRAINT "FK_084cef3785217102f222e90ea7c"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9faba56a12931cf4e38f9dddb49"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_93c464aaf70fb0720dc500e93c8"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_20f8b51fd9655c0b69feed5efc6"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_5332a4daa46fd3f4e6625dd275d"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_c518e3988b9c057920afaf2d8c0"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_54b5dc2739f2dea57900933db66"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_55d9c167993fed3f375391c8e31"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_c5a322ad12a7bf95460c958e80e"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_152b0f8575bdeb47131d9318a66"`);
        await queryRunner.query(`ALTER TABLE "blogs" DROP CONSTRAINT "FK_50205032574e0b039d655f6cfd3"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_f7eec60ca11e796ab5b713516d4"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_a7435dbb7583938d5e7d1376041"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_4875672591221a61ace66f2d4f9"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_e44ddaaa6d058cb4092f83ad61f"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_4548cc4a409b8651ec75f70e280"`);
        await queryRunner.query(`ALTER TABLE "comment_likes" DROP CONSTRAINT "FK_abbd506a94a424dd6a3a68d26f4"`);
        await queryRunner.query(`ALTER TABLE "comment_likes" DROP CONSTRAINT "FK_34d1f902a8a527dbc2502f87c88"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1755b7f4061d5ece60967f00e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a12706e0fd90132ab2ffa9b0b1"`);
        await queryRunner.query(`DROP TABLE "post_files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37d337ad54b1aa6b9a44415a49"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6999d13aca25e33515210abaf1"`);
        await queryRunner.query(`DROP TABLE "post_likes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab673f0e63eac966762155508e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f75f11ca4ed69b941336c5d0e3"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89639a7cf8b3cd156a5d3b9a30"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38c954e266791189dfd7b6ffc4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42589da045825b9fba75e0c51c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a880d68cf02094abb4d55eed54"`);
        await queryRunner.query(`DROP TABLE "analytics_events"`);
        await queryRunner.query(`DROP TABLE "api_keys"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67286c99c7756fb0961b60c58f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dab4d78b3be05c1ca4a626f57f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_047d4304f5141509edcd89820f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_546a6297a776c8413251354225"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TYPE "public"."reports_actiontaken_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_reason_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13c69424c440a0e765053feb4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_371007aca0b12c07d6d2dbdb83"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58575e75914e0b6832685808b1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_442ebfa56e39cc1a9bd8467742"`);
        await queryRunner.query(`DROP TABLE "email_verifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_084cef3785217102f222e90ea7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26d8925842789f2d3b8c093ab3"`);
        await queryRunner.query(`DROP TABLE "user_identities"`);
        await queryRunner.query(`DROP TYPE "public"."user_identities_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ace513fa30d485cfd25c11a9e4"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_authprovider_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df95345b0832f6a18cb4794056"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ffcc26e0e374c307f94ee989d2"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54b5dc2739f2dea57900933db6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c518e3988b9c057920afaf2d8c"`);
        await queryRunner.query(`DROP TABLE "follows"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33d16435acab5d7cb1970157de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c5a322ad12a7bf95460c958e80"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c81be77ac4b528ea4f2c94fcfb"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`DROP TABLE "blogs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a02ba48ab7537f785bdc47b7b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7435dbb7583938d5e7d137604"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7eec60ca11e796ab5b713516d"`);
        await queryRunner.query(`DROP TABLE "files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_36ba37bc75cb1ec04d6d4033e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69f54b3906f28ad3e0f20e684d"`);
        await queryRunner.query(`DROP TABLE "file_contexts"`);
        await queryRunner.query(`DROP TYPE "public"."file_contexts_purpose_enum"`);
        await queryRunner.query(`DROP TYPE "public"."file_contexts_contexttype_enum"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP TABLE "comment_likes"`);
        await queryRunner.query(`DROP TYPE "public"."comment_likes_type_enum"`);
    }

}
