import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateSubscriptionSystem1759079431987 implements MigrationInterface {
    name = 'CreateSubscriptionSystem1759079431987'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "oauth_clients" DROP CONSTRAINT "FK_oauth_clients_userId"`);
        await queryRunner.query(`ALTER TABLE "oauth_tokens" DROP CONSTRAINT "FK_oauth_tokens_clientId"`);
        await queryRunner.query(`ALTER TABLE "oauth_tokens" DROP CONSTRAINT "FK_oauth_tokens_blogId"`);
        await queryRunner.query(`ALTER TABLE "oauth_tokens" DROP CONSTRAINT "FK_oauth_tokens_userId"`);
        await queryRunner.query(`ALTER TABLE "oauth_codes" DROP CONSTRAINT "FK_oauth_codes_clientId"`);
        await queryRunner.query(`ALTER TABLE "oauth_codes" DROP CONSTRAINT "FK_oauth_codes_blogId"`);
        await queryRunner.query(`ALTER TABLE "oauth_codes" DROP CONSTRAINT "FK_oauth_codes_userId"`);
        await queryRunner.query(`DROP INDEX "public"."idx_blogs_is_public"`);
        await queryRunner.query(`DROP INDEX "public"."idx_blogs_id_public"`);
        await queryRunner.query(`DROP INDEX "public"."idx_blogs_id_ispublic"`);
        await queryRunner.query(`DROP INDEX "public"."idx_posts_published_at_desc"`);
        await queryRunner.query(`DROP INDEX "public"."idx_posts_author_published"`);
        await queryRunner.query(`DROP INDEX "public"."idx_posts_id_ispublished_blogid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_posts_id_published"`);
        await queryRunner.query(`DROP INDEX "public"."idx_posts_blogid_ispublished"`);
        await queryRunner.query(`DROP INDEX "public"."idx_posts_id_published_v2"`);
        await queryRunner.query(`DROP INDEX "public"."idx_posts_blogid_ispublished_v2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_oauth_clients_clientId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_oauth_clients_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_oauth_tokens_tokenHash"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_oauth_tokens_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_oauth_tokens_blogId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_oauth_tokens_expiresAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_oauth_codes_code"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_oauth_codes_expiresAt"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_blocks_blocker_blocked"`);
        await queryRunner.query(`DROP INDEX "public"."idx_messages_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_messages_conversationId_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_messages_senderId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_conversations_user1_lastRead"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_conversations_user2_lastRead"`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_plans_tier_enum" AS ENUM('free', 'starter', 'pro')`);
        await queryRunner.query(`CREATE TABLE "subscription_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "displayName" character varying(255), "tier" "public"."subscription_plans_tier_enum" NOT NULL, "features" jsonb NOT NULL, "pricing" jsonb NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "isPopular" boolean NOT NULL DEFAULT false, "badge" character varying, "trialDays" integer NOT NULL DEFAULT '7', "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fa0f49704b17b369c641981806e" UNIQUE ("tier"), CONSTRAINT "PK_9ab8fe6918451ab3d0a4fb6bb0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fa0f49704b17b369c641981806" ON "subscription_plans" ("tier") `);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_tier_enum" AS ENUM('free', 'starter', 'pro')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('active', 'canceled', 'past_due', 'expired', 'trial')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_billingcycle_enum" AS ENUM('monthly', 'yearly')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_paymentprovider_enum" AS ENUM('stripe', 'toss', 'paypal', 'manual')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "planId" uuid, "tier" "public"."subscriptions_tier_enum" NOT NULL DEFAULT 'free', "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'active', "billingCycle" "public"."subscriptions_billingcycle_enum", "startDate" TIMESTAMP, "endDate" TIMESTAMP, "trialEndDate" TIMESTAMP, "nextBillingDate" TIMESTAMP, "canceledAt" TIMESTAMP, "cancelReason" text, "price" numeric(10,2) NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'USD', "autoRenew" boolean NOT NULL DEFAULT true, "paymentProvider" "public"."subscriptions_paymentprovider_enum", "paymentCustomerId" character varying, "paymentSubscriptionId" character varying, "paymentMethodId" character varying, "lastPaymentDate" TIMESTAMP, "lastPaymentAmount" integer, "failedPaymentCount" integer NOT NULL DEFAULT '0', "discountCode" character varying, "discountPercentage" numeric(5,2) NOT NULL DEFAULT '0', "discountEndDate" TIMESTAMP, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97892dded66dbd86b221384f41" ON "subscriptions" ("nextBillingDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_ca1806bbc03217f7cc6a55acab" ON "subscriptions" ("tier") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ccf973355b70645eff37774de" ON "subscriptions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_fbdba4e2ac694cf8c9cecf4dc8" ON "subscriptions" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_history_status_enum" AS ENUM('pending', 'succeeded', 'failed', 'refunded')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_history_paymentprovider_enum" AS ENUM('stripe', 'toss', 'paypal', 'manual')`);
        await queryRunner.query(`CREATE TABLE "payment_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "subscriptionId" uuid, "amount" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'USD', "status" "public"."payment_history_status_enum" NOT NULL DEFAULT 'pending', "paymentProvider" "public"."payment_history_paymentprovider_enum", "transactionId" character varying, "paymentMethodId" character varying, "paymentMethod" text, "description" text, "invoiceUrl" text, "receiptUrl" text, "failureReason" text, "failureCode" character varying, "refundedAt" TIMESTAMP, "refundedAmount" numeric(10,2), "refundReason" text, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5fcec51a769b65c0c3c0987f11c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bf030715478275100f26f6d7c5" ON "payment_history" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_484bf075f2c432da575b7ba9ae" ON "payment_history" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3309cd631d6c3263c550d19ff1" ON "payment_history" ("subscriptionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_34d643de1a588d2350297da5c2" ON "payment_history" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."usage_tracking_resourcetype_enum" AS ENUM('posts', 'storage', 'views', 'api_calls', 'ai_credits')`);
        await queryRunner.query(`CREATE TABLE "usage_tracking" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "resourceType" "public"."usage_tracking_resourcetype_enum" NOT NULL, "count" integer NOT NULL DEFAULT '0', "limit" integer NOT NULL DEFAULT '0', "period" date NOT NULL, "lastUsedAt" TIMESTAMP, "peakUsage" integer NOT NULL DEFAULT '0', "peakUsageAt" TIMESTAMP, "warningsSent" integer NOT NULL DEFAULT '0', "lastWarningAt" TIMESTAMP, "limitReached" boolean NOT NULL DEFAULT false, "limitReachedAt" TIMESTAMP, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cc3efac4d1c6bcf24d6b8fa50fe" UNIQUE ("userId", "resourceType", "period"), CONSTRAINT "PK_2879a43395bb513204f88769aa6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1ffcfcd37100c42bcbf228e217" ON "usage_tracking" ("resourceType") `);
        await queryRunner.query(`CREATE INDEX "IDX_b7b62649ecce8ec1958331b31c" ON "usage_tracking" ("period") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d8df20d681cd50fcde4db2db3" ON "usage_tracking" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_subscriptiontier_enum" AS ENUM('free', 'starter', 'pro')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "subscriptionTier" "public"."users_subscriptiontier_enum" NOT NULL DEFAULT 'free'`);
        await queryRunner.query(`CREATE TYPE "public"."users_subscriptionstatus_enum" AS ENUM('active', 'canceled', 'past_due', 'expired', 'trial')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "subscriptionStatus" "public"."users_subscriptionstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "subscriptionStartDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "subscriptionEndDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "trialEndDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "paymentCustomerId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "paymentSubscriptionId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "paymentMethodId" character varying`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67286c99c7756fb0961b60c58f"`);
        await queryRunner.query(`ALTER TYPE "public"."reports_type_enum" RENAME TO "reports_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."reports_type_enum" AS ENUM('post', 'comment', 'user', 'message')`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "type" TYPE "public"."reports_type_enum" USING "type"::"text"::"public"."reports_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_type_enum_old"`);
        await queryRunner.query(`CREATE INDEX "IDX_c81be77ac4b528ea4f2c94fcfb" ON "posts" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_c5a322ad12a7bf95460c958e80" ON "posts" ("authorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_54b5dc2739f2dea57900933db6" ON "follows" ("follower_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_89481ceb60b67e5e052bf6e16f" ON "oauth_clients" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b0c094fe1ef0a6c4af8f2b10be" ON "oauth_clients" ("clientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_65a43b80d25744e438a6ecd1fd" ON "oauth_tokens" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_b76db67a6b209d6cb3ac65f998" ON "oauth_tokens" ("blogId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8c200cc4c90d24e832caf0a18" ON "oauth_tokens" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_095f87160acedf5dc5a8c9a814" ON "oauth_tokens" ("tokenHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_67286c99c7756fb0961b60c58f" ON "reports" ("type", "targetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe0c99de843e00174b8d34e158" ON "oauth_codes" ("expiresAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9d33ac9c512011dd64af4c8d01" ON "oauth_codes" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_6999d13aca25e33515210abaf1" ON "post_likes" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a12706e0fd90132ab2ffa9b0b1" ON "post_files" ("postId") `);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_7536cba909dd7584a4640cad7d5" FOREIGN KEY ("planId") REFERENCES "subscription_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_history" ADD CONSTRAINT "FK_34d643de1a588d2350297da5c24" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_history" ADD CONSTRAINT "FK_3309cd631d6c3263c550d19ff19" FOREIGN KEY ("subscriptionId") REFERENCES "subscriptions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usage_tracking" ADD CONSTRAINT "FK_5d8df20d681cd50fcde4db2db32" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_clients" ADD CONSTRAINT "FK_89481ceb60b67e5e052bf6e16f6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_tokens" ADD CONSTRAINT "FK_a8c200cc4c90d24e832caf0a180" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_tokens" ADD CONSTRAINT "FK_b76db67a6b209d6cb3ac65f9987" FOREIGN KEY ("blogId") REFERENCES "blogs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_tokens" ADD CONSTRAINT "FK_3d9dfb37837e5dd891bbc81b324" FOREIGN KEY ("clientId") REFERENCES "oauth_clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_codes" ADD CONSTRAINT "FK_4dac391deea4c1f8d24a63107b2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_codes" ADD CONSTRAINT "FK_0d965a63d2832bb967c49e8a2dc" FOREIGN KEY ("blogId") REFERENCES "blogs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_codes" ADD CONSTRAINT "FK_1e80210c80509097733e5194bda" FOREIGN KEY ("clientId") REFERENCES "oauth_clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "oauth_codes" DROP CONSTRAINT "FK_1e80210c80509097733e5194bda"`);
        await queryRunner.query(`ALTER TABLE "oauth_codes" DROP CONSTRAINT "FK_0d965a63d2832bb967c49e8a2dc"`);
        await queryRunner.query(`ALTER TABLE "oauth_codes" DROP CONSTRAINT "FK_4dac391deea4c1f8d24a63107b2"`);
        await queryRunner.query(`ALTER TABLE "oauth_tokens" DROP CONSTRAINT "FK_3d9dfb37837e5dd891bbc81b324"`);
        await queryRunner.query(`ALTER TABLE "oauth_tokens" DROP CONSTRAINT "FK_b76db67a6b209d6cb3ac65f9987"`);
        await queryRunner.query(`ALTER TABLE "oauth_tokens" DROP CONSTRAINT "FK_a8c200cc4c90d24e832caf0a180"`);
        await queryRunner.query(`ALTER TABLE "oauth_clients" DROP CONSTRAINT "FK_89481ceb60b67e5e052bf6e16f6"`);
        await queryRunner.query(`ALTER TABLE "usage_tracking" DROP CONSTRAINT "FK_5d8df20d681cd50fcde4db2db32"`);
        await queryRunner.query(`ALTER TABLE "payment_history" DROP CONSTRAINT "FK_3309cd631d6c3263c550d19ff19"`);
        await queryRunner.query(`ALTER TABLE "payment_history" DROP CONSTRAINT "FK_34d643de1a588d2350297da5c24"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_7536cba909dd7584a4640cad7d5"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a12706e0fd90132ab2ffa9b0b1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6999d13aca25e33515210abaf1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9d33ac9c512011dd64af4c8d01"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0c99de843e00174b8d34e158"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67286c99c7756fb0961b60c58f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_095f87160acedf5dc5a8c9a814"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8c200cc4c90d24e832caf0a18"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b76db67a6b209d6cb3ac65f998"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65a43b80d25744e438a6ecd1fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0c094fe1ef0a6c4af8f2b10be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89481ceb60b67e5e052bf6e16f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54b5dc2739f2dea57900933db6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c5a322ad12a7bf95460c958e80"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c81be77ac4b528ea4f2c94fcfb"`);
        await queryRunner.query(`CREATE TYPE "public"."reports_type_enum_old" AS ENUM('post', 'comment', 'user')`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "type" TYPE "public"."reports_type_enum_old" USING "type"::"text"::"public"."reports_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."reports_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."reports_type_enum_old" RENAME TO "reports_type_enum"`);
        await queryRunner.query(`CREATE INDEX "IDX_67286c99c7756fb0961b60c58f" ON "reports" ("targetId", "type") `);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "paymentMethodId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "paymentSubscriptionId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "paymentCustomerId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "trialEndDate"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "subscriptionEndDate"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "subscriptionStartDate"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "subscriptionStatus"`);
        await queryRunner.query(`DROP TYPE "public"."users_subscriptionstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "subscriptionTier"`);
        await queryRunner.query(`DROP TYPE "public"."users_subscriptiontier_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d8df20d681cd50fcde4db2db3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7b62649ecce8ec1958331b31c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ffcfcd37100c42bcbf228e217"`);
        await queryRunner.query(`DROP TABLE "usage_tracking"`);
        await queryRunner.query(`DROP TYPE "public"."usage_tracking_resourcetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_34d643de1a588d2350297da5c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3309cd631d6c3263c550d19ff1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_484bf075f2c432da575b7ba9ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf030715478275100f26f6d7c5"`);
        await queryRunner.query(`DROP TABLE "payment_history"`);
        await queryRunner.query(`DROP TYPE "public"."payment_history_paymentprovider_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_history_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbdba4e2ac694cf8c9cecf4dc8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ccf973355b70645eff37774de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca1806bbc03217f7cc6a55acab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97892dded66dbd86b221384f41"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_paymentprovider_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_billingcycle_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_tier_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa0f49704b17b369c641981806"`);
        await queryRunner.query(`DROP TABLE "subscription_plans"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_plans_tier_enum"`);
        await queryRunner.query(`CREATE INDEX "IDX_conversations_user2_lastRead" ON "conversations" ("user2Id", "user2LastReadAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_conversations_user1_lastRead" ON "conversations" ("user1Id", "user1LastReadAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_messages_senderId" ON "messages" ("senderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_messages_conversationId_createdAt" ON "messages" ("conversationId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_messages_created_at" ON "messages" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_user_blocks_blocker_blocked" ON "user_blocks" ("blockedId", "blockerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_oauth_codes_expiresAt" ON "oauth_codes" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_oauth_codes_code" ON "oauth_codes" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_oauth_tokens_expiresAt" ON "oauth_tokens" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_oauth_tokens_blogId" ON "oauth_tokens" ("blogId") `);
        await queryRunner.query(`CREATE INDEX "IDX_oauth_tokens_userId" ON "oauth_tokens" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_oauth_tokens_tokenHash" ON "oauth_tokens" ("tokenHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_oauth_clients_userId" ON "oauth_clients" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_oauth_clients_clientId" ON "oauth_clients" ("clientId") `);
        await queryRunner.query(`CREATE INDEX "idx_posts_blogid_ispublished_v2" ON "posts" ("blogId", "isPublished") WHERE ("isPublished" = true)`);
        await queryRunner.query(`CREATE INDEX "idx_posts_id_published_v2" ON "posts" ("id") WHERE ("isPublished" = true)`);
        await queryRunner.query(`CREATE INDEX "idx_posts_blogid_ispublished" ON "posts" ("blogId", "isPublished") WHERE ("isPublished" = true)`);
        await queryRunner.query(`CREATE INDEX "idx_posts_id_published" ON "posts" ("id") WHERE ("isPublished" = true)`);
        await queryRunner.query(`CREATE INDEX "idx_posts_id_ispublished_blogid" ON "posts" ("blogId", "id", "isPublished") `);
        await queryRunner.query(`CREATE INDEX "idx_posts_author_published" ON "posts" ("authorId", "isPublished", "publishedAt") `);
        await queryRunner.query(`CREATE INDEX "idx_posts_published_at_desc" ON "posts" ("isPublished", "publishedAt") WHERE ("isPublished" = true)`);
        await queryRunner.query(`CREATE INDEX "idx_blogs_id_ispublic" ON "blogs" ("id", "isPublic") `);
        await queryRunner.query(`CREATE INDEX "idx_blogs_id_public" ON "blogs" ("id", "isPublic") WHERE ("isPublic" = true)`);
        await queryRunner.query(`CREATE INDEX "idx_blogs_is_public" ON "blogs" ("isPublic") WHERE ("isPublic" = true)`);
        await queryRunner.query(`ALTER TABLE "oauth_codes" ADD CONSTRAINT "FK_oauth_codes_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_codes" ADD CONSTRAINT "FK_oauth_codes_blogId" FOREIGN KEY ("blogId") REFERENCES "blogs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_codes" ADD CONSTRAINT "FK_oauth_codes_clientId" FOREIGN KEY ("clientId") REFERENCES "oauth_clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_tokens" ADD CONSTRAINT "FK_oauth_tokens_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_tokens" ADD CONSTRAINT "FK_oauth_tokens_blogId" FOREIGN KEY ("blogId") REFERENCES "blogs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_tokens" ADD CONSTRAINT "FK_oauth_tokens_clientId" FOREIGN KEY ("clientId") REFERENCES "oauth_clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_clients" ADD CONSTRAINT "FK_oauth_clients_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
